language: node_js

node_js:
  - node

branches:
  only:
    - master

before_install:
  - bin/run-integration npm i -g npm
  - bin/run-integration npm cache verify

install:
  - bin/run-integration npm i -g node-gyp-install
  - bin/run-integration node-gyp-install
  - bin/run-integration npm i --no-optional --no-progress

script:
  - npm run clear
  - npm run prepare
