sudo: true
dist: trusty
language: node_js

node_js:
  - node

branches:
  only:
    - development
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

after_install:
  - npm rebuild node-sass

script:
  - npm run clear
  - npm run prepare
