language: node_js

node_js:
  - node

branches:
  only:
    - master

before_install:
  - npm i -g npm
  - npm cache verify

install:
  - npm i -g node-gyp-install
  - node-gyp-install
  - npm i --no-optional --no-progress

script:
  - npm run clear
  - npm run prepare
