sudo: true
dist: trusty
language: node_js

node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm
  - npm cache verify

install:
  - npm i --no-optional --no-progress

script:
  - npm run clear
  - npm run prepare
